# Use an official Node.js runtime as a parent image
FROM node:20.16.0-alpine

# Set the working directory in the container
WORKDIR /app

# Install dependencies
COPY package.json pnpm-lock.yaml ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose port 5173 (default Vite port)
EXPOSE 5173

# Command to run the development server
CMD ["npm", "run", "dev"]
