version: "3.8"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres_password
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev  # Change to `Dockerfile` for production
    ports:
      - "3500:80"
    depends_on:
      - api
      - client
    restart: always    
  api:
    build:
      dockerfile: Dockerfile.dev # Change to `Dockerfile` for production
      context: "./server"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev # Change to `Dockerfile` for production
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
